services:
  postgres-db:
    image: postgres:16-alpine
    container_name: medical-clinic-db-for-proxy
    environment:
      POSTGRES_DB: medical_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "228007"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medical_clinic"]
      interval: 3s
      timeout: 3s
      retries: 3

  medical-clinic-app:
    build: ../../medical-clinic/medical-clinic
    container_name: medical-clinic-app-for-proxy
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/medical_clinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "228007"
    ports:
      - "8080:8080"

  medical-clinic-proxy:
    build: .
    container_name: medical-clinic-proxy
    depends_on:
      - medical-clinic-app
    environment:
      SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_MEDICAL-CLINIC-CLIENT_URL: http://medical-clinic-app:8080
      MEDICAL_CLINIC_URL: http://medical-clinic-app:8080
    ports:
      - "8081:8081"

volumes:
  pgdata: